// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Dir(req: $models.BrowseDirRequest): $CancellablePromise<$models.BrowseDirResponse | null> {
    return $Call.ByID(1873593121, req);
}

export function OpenFile(relPath: string): $CancellablePromise<void> {
    return $Call.ByID(1256274500, relPath);
}

export function PickDir(initial: string): $CancellablePromise<$models.PickDirectoryResult | null> {
    return $Call.ByID(1834131498, initial);
}

export function SearchByName(req: $models.BrowseSearchRequest): $CancellablePromise<$models.BrowseSearchResponse | null> {
    return $Call.ByID(2051607664, req);
}
