// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contract$0 from "../contract/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AutoCommit(): $CancellablePromise<$models.AutoCommitResult | null> {
    return $Call.ByID(2490988510);
}

export function AutoCommitWithFiles(files: string[] | null): $CancellablePromise<$models.AutoCommitResult | null> {
    return $Call.ByID(965131421, files);
}

export function Diff(hash: string): $CancellablePromise<contract$0.DiffStat | null> {
    return $Call.ByID(3654344423, hash);
}

export function Files(hash: string): $CancellablePromise<$models.CommitFilesByHashResponse | null> {
    return $Call.ByID(3873784959, hash);
}

export function List(): $CancellablePromise<$models.CommitListResponse | null> {
    return $Call.ByID(331401160);
}

export function Manual(req: $models.ManualCommitRequest): $CancellablePromise<$models.ManualCommitResult | null> {
    return $Call.ByID(2825375678, req);
}

export function Status(): $CancellablePromise<$models.CommitStatusResponse | null> {
    return $Call.ByID(3623812258);
}

export function Suggest(): $CancellablePromise<$models.SuggestCommitResult | null> {
    return $Call.ByID(1442856538);
}

export function TreeAt(hash: string): $CancellablePromise<$models.CommitTreeAtResponse | null> {
    return $Call.ByID(1653710893, hash);
}
