// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Health(): $CancellablePromise<string> {
    return $Call.ByID(1782280520);
}

export function Info(): $CancellablePromise<$models.DiagnosticsInfo | null> {
    return $Call.ByID(732460570);
}

export function Ready(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3257803081);
}
