// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contract$0 from "../contract/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CommitFileContent(hash: string, path: string): $CancellablePromise<string> {
    return $Call.ByID(4047726283, hash, path);
}

export function DownloadHistory(relPath: string, hash: string): $CancellablePromise<string> {
    return $Call.ByID(2463316867, relPath, hash);
}

export function Get(id: number): $CancellablePromise<contract$0.FileInfo | null> {
    return $Call.ByID(3806268943, id);
}

export function History(id: number): $CancellablePromise<$models.FileHistoryResponse | null> {
    return $Call.ByID(2610358519, id);
}

export function List(req: $models.FileListRequest): $CancellablePromise<$models.FileListResponse | null> {
    return $Call.ByID(2155153897, req);
}

export function Recent(req: $models.FileListRequest): $CancellablePromise<$models.RecentFilesResponse | null> {
    return $Call.ByID(1177752118, req);
}

export function Resolve(relPath: string): $CancellablePromise<number> {
    return $Call.ByID(431433307, relPath);
}

export function Restore(req: $models.RestoreFileRequest): $CancellablePromise<void> {
    return $Call.ByID(3646643481, req);
}

export function Retry(id: number): $CancellablePromise<void> {
    return $Call.ByID(115937633, id);
}

export function UpdateTags(req: $models.UpdateTagsRequest): $CancellablePromise<void> {
    return $Call.ByID(2214478565, req);
}
