// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as browser$0 from "../browser/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contract$0 from "../contract/models.js";

/**
 * AutoCommitResult 自动提交结果
 */
export interface AutoCommitResult {
    "skipped": boolean;
    "hash"?: string;
    "message"?: string;
    "ai"?: string;
}

/**
 * BrowseDirRequest 浏览目录请求
 */
export interface BrowseDirRequest {
    "path": string;
}

/**
 * BrowseDirResponse 浏览目录响应
 */
export interface BrowseDirResponse {
    "entries": (browser$0.DirEntry | null)[] | null;
}

/**
 * BrowseSearchRequest 文件搜索请求
 */
export interface BrowseSearchRequest {
    "q": string;
    "limit": number;
}

/**
 * BrowseSearchResponse 文件搜索响应
 */
export interface BrowseSearchResponse {
    "results": (browser$0.SearchResult | null)[] | null;
    "total": number;
}

/**
 * CommitFileStatus 提交文件状态
 */
export interface CommitFileStatus {
    "relPath": string;
    "code": string;
}

/**
 * CommitFilesByHashResponse 按哈希取提交改动文件
 */
export interface CommitFilesByHashResponse {
    "files": (contract$0.CommitFile | null)[] | null;
}

/**
 * CommitListResponse 提交列表
 */
export interface CommitListResponse {
    "commits": (contract$0.CommitInfo | null)[] | null;
}

/**
 * CommitStatusResponse 提交状态响应
 */
export interface CommitStatusResponse {
    "files": CommitFileStatus[] | null;
    "count": number;
}

/**
 * CommitTreeAtResponse 按哈希取快照文件
 */
export interface CommitTreeAtResponse {
    "files": (contract$0.VersionFile | null)[] | null;
}

/**
 * DiagnosticsInfo 诊断信息
 */
export interface DiagnosticsInfo {
    "version": string;
    "generation": string;
    "queueDepth": number;
    "storageOk": boolean;
}

/**
 * FileHistoryResponse 文件历史版本
 */
export interface FileHistoryResponse {
    "commits": (contract$0.CommitInfo | null)[] | null;
}

/**
 * FileListRequest 文件列表请求
 * WindowHours 仅 Recent 使用：最近 N 小时内修改的文件（0 = 全部）
 */
export interface FileListRequest {
    "status": string;
    "tag": string;
    "page": number;
    "pageSize": number;
    "sort": string;
    "windowHours": number;
}

/**
 * FileListResponse 文件列表响应
 */
export interface FileListResponse {
    "items": (contract$0.FileInfo | null)[] | null;
    "total": number;
    "page": number;
}

/**
 * InitRequest 工作区初始化请求
 * 结构与迁移前的 POST /api/workspace/init 一致：工作区路径 + 可选的 markitdown/llm/embed/rerank 配置区块，
 * 初始化时一并落盘（修复：此前仅传 workspace，向导/设置页填写的 AI 配置被静默丢弃）。
 */
export interface InitRequest {
    "workspace": string;
    "markitdown": {"pythonPath": string, "command": string};
    "llm": {"baseUrl": string, "apiKey": string, "model": string, "temperature": number} | null;
    "embed": {"baseUrl": string, "apiKey": string, "model": string, "dimensions": number};
    "rerank": {"baseUrl": string, "apiKey": string, "model": string};
}

/**
 * LLMTestRequest
 */
export interface LLMTestRequest {
    /**
     * chat|embed|rerank|models
     */
    "type": string;
    "baseUrl": string;
    "apiKey": string;
    "model": string;
    "temperature": number;
    "kind": string;
}

/**
 * LLMTestResult LLM 测试结果
 */
export interface LLMTestResult {
    "ok": boolean;
    "message": string;
    "models"?: string[] | null;
}

/**
 * ManualCommitRequest 手动提交请求
 */
export interface ManualCommitRequest {
    "message": string;
}

/**
 * ManualCommitResult 手动提交结果
 */
export interface ManualCommitResult {
    "hash": string;
    "skipped": boolean;
}

/**
 * MarkitdownProbeResult MarkItDown 探测结果（版本 + 位置）
 */
export interface MarkitdownProbeResult {
    "path": string;
    "version"?: string;
    "ok": boolean;
    "error"?: string;
}

export interface PickDirRequest {
    "initial": string;
    "kind": string;
}

/**
 * PickDirectoryResult 目录选择结果
 */
export interface PickDirectoryResult {
    "path": string;
}

/**
 * PythonDetectResult Python 探测结果
 */
export interface PythonDetectResult {
    "path": string;
    "ok": boolean;
    "version"?: string;
    "markitdownCmd"?: string;
    "markitdownVersion"?: string;
    "error"?: string;
}

/**
 * QAMessagesResponse 消息列表响应
 */
export interface QAMessagesResponse {
    "messages": (contract$0.QAMessage | null)[] | null;
}

/**
 * QASessionsResponse 会话列表响应
 */
export interface QASessionsResponse {
    "sessions": (contract$0.QASession | null)[] | null;
}

/**
 * QAStreamRequest 流式问答请求
 */
export interface QAStreamRequest {
    "question": string;
    "mode": string;
    "fileId": number;
    "sessionId": number;

    /**
     * RequestID 前端生成的流式事件 id（qa:chunk:<id> / qa:done:<id> / qa:error:<id>）。
     * 事件名是"前端订阅名 vs 后端 emit 名"的双向握手协议，id 必须由同一侧生成并回传，
     * 否则前后端各自生成、永不匹配（修复：问答事件收不到、sending 卡死）。
     */
    "requestId": string;
}

/**
 * QueueStatusResponse 队列状态响应
 */
export interface QueueStatusResponse {
    "running": number;
    "pending": number;
    "paused": boolean;
}

/**
 * RecentFilesResponse 最近文件响应
 */
export interface RecentFilesResponse {
    "items": (contract$0.FileInfo | null)[] | null;
    "window": number;
}

/**
 * RestoreFileRequest 恢复文件请求
 */
export interface RestoreFileRequest {
    "id": number;
    "commitHash": string;
}

/**
 * SearchRequest 搜索请求
 */
export interface SearchRequest {
    "q": string;
    "tag": string;
    "page": number;
    "tagFilter": string[] | null;
}

/**
 * SearchResponse 搜索响应
 */
export interface SearchResponse {
    "items": (contract$0.SearchResult | null)[] | null;
    "total": number;
    "page": number;
}

/**
 * SetStatsEnabledRequest
 */
export interface SetStatsEnabledRequest {
    "enabled": boolean;
}

/**
 * StatsRequest 统计请求
 */
export interface StatsRequest {
    "range": string;
    "from": number;
    "to": number;
}

/**
 * StatsResponse 统计响应
 */
export interface StatsResponse {
    "enabled": boolean;
    "metrics": contract$0.StatsMetrics | null;
}

/**
 * SuggestCommitResult 建议提交消息
 */
export interface SuggestCommitResult {
    "suggestion": string;
}

/**
 * TagSuggestionsResponse 标签建议响应
 */
export interface TagSuggestionsResponse {
    "suggestions": (contract$0.TagSuggestion | null)[] | null;
}

/**
 * TagsListResponse 标签库响应
 */
export interface TagsListResponse {
    "tags": (contract$0.TagInfo | null)[] | null;
}

/**
 * TestMarkItDownRequest
 */
export interface TestMarkItDownRequest {
    "pythonPath": string;
    "command": string;
}

/**
 * UpdateSecretsRequest 更新密钥请求
 */
export interface UpdateSecretsRequest {
    "llmApiKey": string;
    "embedApiKey": string;
    "rerankApiKey": string;
}

/**
 * UpdateSettingsResult 更新设置结果
 */
export interface UpdateSettingsResult {
    "restartRequired": string[] | null;
    "reindexRequired": boolean;
}

/**
 * UpdateTagsRequest 更新文件标签
 */
export interface UpdateTagsRequest {
    "id": number;
    "add": string[] | null;
    "remove": string[] | null;
}

/**
 * WorkspaceInfo 工作区信息（返回给前端）
 * 字段形状与迁移前的 /api/workspace/info 保持一致（initialized/workspacePath/dirtyCounts/configured），
 * 前端 stores/workspace.ts 依赖这些字段判断"是否已初始化"。
 */
export interface WorkspaceInfo {
    "workspace": string;
    "workspacePath": string;
    "initialized": boolean;
    "dataDir": string;
    "generation": string;
    "version": string;
    "commit": string;
    "buildTime": string;
    "config": { [_ in string]?: any } | null;
    "head"?: contract$0.HeadInfo | null;
    "dirtyCounts"?: { [_ in string]?: number } | null;
    "markitdownConfigured": boolean;
    "llmConfigured": boolean;
    "embedConfigured": boolean;
}
