// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AskStream 流式问答：在 goroutine 中执行，通过 Wails 全局事件向所有已连接窗口推送 chunk/done/error。
 * 参数 windowName 为保留参数（当前通过 application.Get() 广播到所有窗口）。
 */
export function AskStream(req: $models.QAStreamRequest, $1: string): $CancellablePromise<void> {
    return $Call.ByID(2111051771, req, $1);
}

export function DeleteSession(id: number): $CancellablePromise<void> {
    return $Call.ByID(471488507, id);
}

export function Messages(sessionID: number): $CancellablePromise<$models.QAMessagesResponse | null> {
    return $Call.ByID(765408186, sessionID);
}

export function Sessions(): $CancellablePromise<$models.QASessionsResponse | null> {
    return $Call.ByID(1043124355);
}
