// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Pause(): $CancellablePromise<void> {
    return $Call.ByID(2555499053);
}

export function Resume(): $CancellablePromise<void> {
    return $Call.ByID(2029192842);
}

export function Status(): $CancellablePromise<$models.QueueStatusResponse | null> {
    return $Call.ByID(872733455);
}
