// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Get(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(240962595);
}

export function Relocate(workspace: string): $CancellablePromise<void> {
    return $Call.ByID(4268151878, workspace);
}

export function UpdateSecrets(req: $models.UpdateSecretsRequest): $CancellablePromise<void> {
    return $Call.ByID(3788620861, req);
}

/**
 * updateSettings 处理一般设置更新，识别需要重启/重建索引的键
 */
export function UpdateSettings(settings: { [_ in string]?: any } | null): $CancellablePromise<$models.UpdateSettingsResult | null> {
    return $Call.ByID(3885492637, settings);
}
