// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Export(format: string, req: $models.StatsRequest): $CancellablePromise<string> {
    return $Call.ByID(138858583, format, req);
}

export function Get(req: $models.StatsRequest): $CancellablePromise<$models.StatsResponse | null> {
    return $Call.ByID(4293338803, req);
}

export function Purge(): $CancellablePromise<void> {
    return $Call.ByID(122607792);
}

export function SetEnabled(req: $models.SetStatsEnabledRequest): $CancellablePromise<void> {
    return $Call.ByID(4193981180, req);
}
