// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AcceptSuggestion(id: number): $CancellablePromise<void> {
    return $Call.ByID(3134982805, id);
}

export function List(): $CancellablePromise<$models.TagsListResponse | null> {
    return $Call.ByID(1605203397);
}

export function RejectSuggestion(id: number): $CancellablePromise<void> {
    return $Call.ByID(573942910, id);
}

export function Suggestions(): $CancellablePromise<$models.TagSuggestionsResponse | null> {
    return $Call.ByID(1116907694);
}
