// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contract$0 from "../contract/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DetectPython(): $CancellablePromise<$models.PythonDetectResult | null> {
    return $Call.ByID(2625130181);
}

/**
 * ProbeMarkitdown 基于指定 Python（为空时自动探测）返回 markitdown 位置与版本
 */
export function ProbeMarkitdown(pythonPath: string): $CancellablePromise<$models.MarkitdownProbeResult | null> {
    return $Call.ByID(596994890, pythonPath);
}

export function TestLLM(req: $models.LLMTestRequest): $CancellablePromise<$models.LLMTestResult | null> {
    return $Call.ByID(2894649063, req);
}

export function TestMarkItDown(req: $models.TestMarkItDownRequest): $CancellablePromise<contract$0.ProbeResult | null> {
    return $Call.ByID(229971064, req);
}
