// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkspaceService 工作区（初始化、状态、诊断）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Info(): $CancellablePromise<$models.WorkspaceInfo | null> {
    return $Call.ByID(3094927867);
}

export function Init(req: $models.InitRequest): $CancellablePromise<void> {
    return $Call.ByID(2744319081, req);
}
