// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CommitFile 单个提交内改动的文件
 */
export interface CommitFile {
    "path": string;

    /**
     * added|modified|deleted
     */
    "status": string;
}

/**
 * CommitInfo 提交信息
 */
export interface CommitInfo {
    "hash": string;
    "time": number;
    "message": string;
    "author": string;
}

export interface DayCount {
    "date": string;
    "count": number;
}

export interface DiffStat {
    "added": number;
    "modified": number;
    "deleted": number;
    "files"?: string[] | null;
}

export interface FileChanges {
    "added": number;
    "modified": number;
    "deleted": number;
}

/**
 * FileInfo 文件元数据
 */
export interface FileInfo {
    "id": number;
    "relPath": string;
    "size": number;

    /**
     * 毫秒
     */
    "mtime": number;
    "contentHash"?: string;

    /**
     * pdf/docx/pptx/xlsx/txt/md/doc(ignored)
     */
    "docType": string;
    "indexStatus": string;
    "lastError"?: string;
    "firstSeenAt": number;
    "lastIndexedAt"?: number;
}

/**
 * FileTag 文件-标签关联
 */
export interface FileTag {
    "name": string;

    /**
     * auto|manual
     */
    "origin": string;
}

/**
 * HeadInfo 当前版本（HEAD）概要
 */
export interface HeadInfo {
    "hash": string;

    /**
     * 当前分支名（无提交时为 master）
     */
    "branch"?: string;

    /**
     * 当前提交树上文件总数
     */
    "countFiles": number;

    /**
     * 相对上一提交改动的文件数
     */
    "changedFiles": number;
    "hasCommits": boolean;
}

export interface HotFile {
    "relPath": string;
    "count": number;
}

export interface HourBuckets {
    "morning": number;
    "afternoon": number;
    "evening": number;
    "night": number;
}

export interface ProbeResult {
    "ok": boolean;
    "message": string;
}

/**
 * QAMessage 问答消息
 */
export interface QAMessage {
    "id": number;
    "sessionId": number;

    /**
     * user|assistant
     */
    "role": string;
    "content": string;

    /**
     * JSON
     */
    "sources"?: string;
    "createdAt": number;
}

/**
 * QASession 问答会话
 */
export interface QASession {
    "id": number;
    "createdAt": number;

    /**
     * file|global
     */
    "mode": string;
    "fileId"?: number;
    "messageCount": number;
}

/**
 * SearchResult 搜索结果项
 */
export interface SearchResult {
    "fileId": number;
    "relPath": string;
    "hitText": string;
    "score": number;
    "tags": FileTag[] | null;
    "mtime": number;
    "matchedChunks": number;
}

/**
 * StatsMetrics 统计指标
 */
export interface StatsMetrics {
    "commitsByDay": DayCount[] | null;
    "fileChanges": FileChanges;
    "hotFiles": HotFile[] | null;
    "hourBuckets": HourBuckets;
    "tagDistribution": TagCount[] | null;
    "iterationRate": number;
}

export interface TagCount {
    "tag": string;
    "count": number;
}

/**
 * TagInfo 标签
 */
export interface TagInfo {
    "id": number;
    "name": string;

    /**
     * predefined|auto_generated|user_confirmed
     */
    "source": string;
    "count"?: number;
    "createdAt": number;
}

/**
 * TagSuggestion 标签建议
 */
export interface TagSuggestion {
    "id": number;
    "name": string;
    "reason"?: string;
    "fileId": number;
    "relPath"?: string;

    /**
     * pending|accepted|rejected
     */
    "status": string;
    "createdAt": number;
}

/**
 * VersionFile 某提交快照中的文件条目（用于"查看该提交的全部文件"）
 */
export interface VersionFile {
    "path": string;
    "size": number;

    /**
     * pdf/docx/pptx/xlsx/txt/md/doc(ignored)；空表示不支持
     */
    "docType"?: string;
}
