// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DirEntry 目录中的一个条目（子目录或文件）
 */
export interface DirEntry {
    /**
     * 名称（不含路径）
     */
    "name": string;

    /**
     * 相对工作区根（目录以 / 结尾；根目录为空）
     */
    "relPath": string;
    "isDir": boolean;
    "size"?: number;

    /**
     * 毫秒
     */
    "mtime"?: number;

    /**
     * 文档类型（不支持的为空）
     */
    "docType"?: string;

    /**
     * 是否为受支持的、可建立索引的文档类型
     */
    "indexable": boolean;

    /**
     * indexed / pending / failed / ignored / ''（未入索引库）
     */
    "indexStatus"?: string;
}

/**
 * SearchResult 文件名搜索命中项
 */
export interface SearchResult {
    "relPath": string;
    "isDir": boolean;
    "size"?: number;
    "mtime"?: number;
    "docType"?: string;
    "indexable": boolean;
}
